package com.artica.telesalud.patientmasterindex.model;
// Generated Apr 10, 2014 4:47:08 PM by Hibernate Tools 3.6.0



/**
 * Domains generated by hbm2java
 */
public class Domains  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
     private String name;

    public Domains() {
    }

	
    public Domains(String uuid, String name) {
        this.uuid = uuid;
        this.name = name;
    }
 
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


