package com.artica.telesalud.patientmasterindex.model;
// Generated Apr 10, 2014 4:47:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Ehr generated by hbm2java
 */
public class Ehr  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
     private String name;
     private Date creationDate;

    public Ehr() {
    }

	
    public Ehr(String uuid, String name, Date creationDate) {
        this.uuid = uuid;
        this.name = name;
        this.creationDate = creationDate;
    }

    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
  




}


